insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Lasagna','60','tanta roba','primo')
insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Patate','60','tanta roba','primo')
insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Zucchine','60','tanta roba','primo')
insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Carote','60','tanta roba','primo')
insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Pasta','60','tanta roba','primo')
insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Tiramisu','60','tanta roba','primo')
insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Pollo','60','tanta roba','primo')
insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Pesce','60','tanta roba','primo')
insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Formaggio Fuso','60','tanta roba','primo')
insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Torta di Mele','60','tanta roba','primo')
insert into ricetta(id,nome,tempo_preparazione_tot,descrizione,tipologia) values(nextval('ricetta_seq'),'Zabaione','60','tanta roba','primo')